import type { NextConfig } from "next";

const legacyRedirects = [
    { source: '/dashboard', destination: '/apps', permanent: false },
    { source: '/hr-dashboard', destination: '/m/pilotage', permanent: false },
    { source: '/activities', destination: '/m/pilotage/activities', permanent: false },
    { source: '/activities/:path*', destination: '/m/pilotage/activities/:path*', permanent: false },
    { source: '/reports', destination: '/m/pilotage/reports', permanent: false },
    { source: '/employees', destination: '/m/personnel/employees', permanent: false },
    { source: '/employees/:path*', destination: '/m/personnel/employees/:path*', permanent: false },
    { source: '/contracts', destination: '/m/personnel/contracts', permanent: false },
    { source: '/contracts/:path*', destination: '/m/personnel/contracts/:path*', permanent: false },
    { source: '/departments', destination: '/m/personnel/departments', permanent: false },
    { source: '/departments/:path*', destination: '/m/personnel/departments/:path*', permanent: false },
    { source: '/positions', destination: '/m/personnel/positions', permanent: false },
    { source: '/positions/:path*', destination: '/m/personnel/positions/:path*', permanent: false },
    { source: '/documents', destination: '/m/personnel/documents', permanent: false },
    { source: '/documents/:path*', destination: '/m/personnel/documents/:path*', permanent: false },
    { source: '/onboarding', destination: '/m/personnel/onboarding', permanent: false },
    { source: '/onboarding/:path*', destination: '/m/personnel/onboarding/:path*', permanent: false },
    { source: '/offboarding', destination: '/m/personnel/offboarding', permanent: false },
    { source: '/offboarding/:path*', destination: '/m/personnel/offboarding/:path*', permanent: false },
    { source: '/mobility', destination: '/m/personnel/mobility', permanent: false },
    { source: '/mobility/:path*', destination: '/m/personnel/mobility/:path*', permanent: false },
    { source: '/job-families', destination: '/m/personnel/job-families', permanent: false },
    { source: '/job-families/:path*', destination: '/m/personnel/job-families/:path*', permanent: false },
    { source: '/grades', destination: '/m/personnel/grades', permanent: false },
    { source: '/grades/:path*', destination: '/m/personnel/grades/:path*', permanent: false },
    { source: '/job-roles', destination: '/m/personnel/job-roles', permanent: false },
    { source: '/job-roles/:path*', destination: '/m/personnel/job-roles/:path*', permanent: false },
    { source: '/career-paths', destination: '/m/personnel/career-paths', permanent: false },
    { source: '/career-paths/:path*', destination: '/m/personnel/career-paths/:path*', permanent: false },
    { source: '/skills', destination: '/m/personnel/skills', permanent: false },
    { source: '/skills/:path*', destination: '/m/personnel/skills/:path*', permanent: false },
    { source: '/leave', destination: '/m/temps/leave', permanent: false },
    { source: '/leave/:path*', destination: '/m/temps/leave/:path*', permanent: false },
    { source: '/attendance', destination: '/m/temps/attendance', permanent: false },
    { source: '/attendance/:path*', destination: '/m/temps/attendance/:path*', permanent: false },
    { source: '/compensation', destination: '/m/paie/compensation', permanent: false },
    { source: '/compensation/:path*', destination: '/m/paie/compensation/:path*', permanent: false },
    { source: '/benefits', destination: '/m/paie/benefits', permanent: false },
    { source: '/benefits/:path*', destination: '/m/paie/benefits/:path*', permanent: false },
    { source: '/payroll', destination: '/m/paie/payroll', permanent: false },
    { source: '/recruitment', destination: '/m/recrutement/demandes', permanent: false },
    { source: '/recruitment/:path*', destination: '/m/recrutement/demandes/:path*', permanent: false },
    { source: '/job-offers', destination: '/m/recrutement/offres', permanent: false },
    { source: '/job-offers/:path*', destination: '/m/recrutement/offres/:path*', permanent: false },
    { source: '/applications', destination: '/m/recrutement/candidatures', permanent: false },
    { source: '/applications/:path*', destination: '/m/recrutement/candidatures/:path*', permanent: false },
    { source: '/training/sessions', destination: '/m/formation/sessions', permanent: false },
    { source: '/training/sessions/:path*', destination: '/m/formation/sessions/:path*', permanent: false },
    { source: '/training/catalog', destination: '/m/formation/catalog', permanent: false },
    { source: '/training/catalog/:path*', destination: '/m/formation/catalog/:path*', permanent: false },
    { source: '/training', destination: '/m/formation/demandes', permanent: false },
    { source: '/training/:path*', destination: '/m/formation/demandes/:path*', permanent: false },
    { source: '/evaluation-cycles', destination: '/m/performance/cycles', permanent: false },
    { source: '/evaluation-cycles/:path*', destination: '/m/performance/cycles/:path*', permanent: false },
    { source: '/objectives', destination: '/m/performance/objectifs', permanent: false },
    { source: '/objectives/:path*', destination: '/m/performance/objectifs/:path*', permanent: false },
    { source: '/career-plans', destination: '/m/performance/career-plans', permanent: false },
    { source: '/career-plans/:path*', destination: '/m/performance/career-plans/:path*', permanent: false },
    { source: '/succession-plans', destination: '/m/performance/succession-plans', permanent: false },
    { source: '/succession-plans/:path*', destination: '/m/performance/succession-plans/:path*', permanent: false },
    { source: '/profiles', destination: '/m/securite/profiles', permanent: false },
    { source: '/profiles/:path*', destination: '/m/securite/profiles/:path*', permanent: false },
    { source: '/users', destination: '/m/securite/users', permanent: false },
    { source: '/users/:path*', destination: '/m/securite/users/:path*', permanent: false },
    { source: '/settings', destination: '/m/securite/settings', permanent: false },
    { source: '/profile', destination: '/m/securite/settings', permanent: false },
];

const nextConfig: NextConfig = {
    async redirects() {
        return legacyRedirects;
    },
};

export default nextConfig;
